/** Declaration file generated by dts-gen */

export class SolGrep {
    constructor(...args: any[]);

    analyzeDir(...args: any[]): void;

    analyzeDirQueue(...args: any[]): void;

    analyzeFile(...args: any[]): void;

    close(...args: any[]): void;

    notify(...args: any[]): void;

    notifyRules(...args: any[]): void;

    report(...args: any[]): void;

}

export namespace rules {
    class DupeFinder {
        constructor(...args: any[]);

        onClose(...args: any[]): void;

        onDirAnalyzed(...args: any[]): void;

        onProcess(...args: any[]): void;

        static description: string;

    }

    class GenericGrep {
        constructor(...args: any[]);

        onProcess(...args: any[]): void;

        static description: string;

    }

    class IsInitializable {
        constructor(...args: any[]);

        onProcess(...args: any[]): void;

        static description: string;

    }

    class IsMultipleBalanceOfSameFunc {
        constructor(...args: any[]);

        onProcess(...args: any[]): void;

        static description: string;

    }

    class Stats {
        constructor(...args: any[]);

        onClose(...args: any[]): void;

        onDirAnalyzed(...args: any[]): void;

        onProcess(...args: any[]): void;

        static description: string;

    }

}

